### ISSUE TITLE
Add storeChallenge to example

### ISSUE THREAD

**Issue by maggie44** [atinux/nuxt-todo-passkeys#1]
It says in the auth plugin docs it is “highly recommended” to use the storeChallenge approach for security best practices to prevent replay attacks. It should probably be included in the example? 

https://github.com/atinux/nuxt-auth-utils?tab=readme-ov-file#webauthn-passkey

**Comment by atinux** [comment]
I believe this should be quite easy to do by leveraging [NuxtHub KV](https://hub.nuxt.com/docs/features/kv), if you want to try feel free to open a PR?

**Comment by atinux** [comment]
Checkout #3 to see how I implemented it!

**Comment by maggie44** [comment]
Thanks for adding the example.

It looks though like there is an issue with the auth. Even on the demo site for this repo, when you create an account it creates fine, but when trying to sign in it says `Challenge not found or expired` on every attempt, preventing any login. 

https://todo-passkeys.nuxt.dev/

**Comment by maggie44** [comment]
> Thanks for adding the example.
> 
> It looks though like there is an issue with the auth. Even on the demo site for this repo, when you create an account it creates fine, but when trying to sign in it says `Challenge not found or expired` on every attempt, preventing any login.
> 
> https://todo-passkeys.nuxt.dev/

If someone is coming across this issue with the same problem, the fix is to apply the example linked to in the PR https://github.com/atinux/nuxt-todo-passkeys/pull/3 as mentioned above, but also to apply the fix added in this commit: https://github.com/atinux/nuxt-todo-passkeys/commit/08d12706405825a291ca6dd4793f8f681bb24849
