### ISSUE TITLE
How to use with 'Discoverable credentials' / 'resident keys'?

### ISSUE THREAD

**Issue by anbraten** [atinux/nuxt-todo-passkeys#2]
Currently it is required to enter a username to login. Instead it would be interesting to login by just clicking the login button.

**Comment by atinux** [comment]
You don't need to fill the login actually:

https://github.com/user-attachments/assets/b38ed4a4-6a1b-45a8-bb26-6ce46f5e5cf8

This is up to you on how you implement it, this is just a demo :)
